echo "######start setup $HOME######"
mklink "c:%HOMEPATH%\.inputrc" "c:%HOMEPATH%\Dropbox\Documents\env\.inputrc"
echo "######start setup zsh######"
mklink "c:%HOMEPATH%\.zshrc" "c:%HOMEPATH%\Dropbox\Documents\env\.zshrc"
mklink "c:%HOMEPATH%\.zshenv" "c:%HOMEPATH%\Dropbox\Documents\env\.zshenv"
mklink "c:%HOMEPATH%\.zshrc.cygwin" "c:%HOMEPATH%\Dropbox\Documents\env\.zshrc.cygwin.sh"
echo "######finished setup zsh######"
echo "######finished setup $HOME######"

echo "######start setup tex######"
mklink /D "c:\w32tex\share\texmf-local" "c:%HOMEPATH%\Dropbox\Documents\env\texmf-local"
echo "######finished setup tex######"

echo "######start setup vim######"
mklink "c:%HOMEPATH%\_vimrc" "c:%HOMEPATH%\Dropbox\Documents\env\.vimrc"
mklink "c:%HOMEPATH%\_gvimrc" "c:%HOMEPATH%\Dropbox\Documents\env\.gvimrc"
mklink /D "c:%HOMEPATH%\vimfiles" "c:%HOMEPATH%\Dropbox\Documents\env\.vim"
echo " git clone git://github.com/Shougo/neobundle.vim ./.vim/bundle/neobundle.vim"
echo " vi +NeoBundleInstall +q"
echo "######finished setup vim plugins######"
echo "######start setup vim utils######"
mklink "c:%HOMEPATH%\_vrapperrc" "c:%HOMEPATH%\Dropbox\Documents\env\.vrapperrc"
mklink "c:%HOMEPATH%\_viemurc" "c:%HOMEPATH%\Dropbox\Documents\env\_viemurc"
mklink "c:%HOMEPATH%\.ideavimrc" "c:%HOMEPATH%\Dropbox\Documents\env\.xvimrc"
mklink "c:%HOMEPATH%\.vsvimrc" "c:%HOMEPATH%\Dropbox\Documents\env\.xvimrc"
echo "######finished setup vim utils######"
pause
