#!/bin/sh
dropbox=~/Dropbox/Documents/env/
if [ ! -d $dropbox ]; then
    exit;
else
    tmptar=tmp.$$.tar
    files="$(git log -n 1 --name-status --oneline | \
        awk 'NR >= 2 && !/^.gitignore/ { if ($1 != "D") print $2 }')"
    echo "$files" | tar -cz -T - -f $tmptar
    if [ $? -eq 0 ]; then
        echo "########## Sync Dropbox #####################"
        for a in ${files[@]}
        do
            echo "copy $a -> $dropbox"
        done
        if [ -f $tmptar ]; then
            `mv $tmptar $dropbox; cd $dropbox; tar xfz $tmptar; rm $tmptar`
        fi
        echo "############################################"
    else
        rm $tmptar
    fi
fi

