#!/bin/sh
if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

f=`git diff-index --name-status $against -- | grep 'githooks/post-commit' | cut -c3-`
cp $f .git/hooks/

